version: '3.8'
services:
  flask-server:
    build: ./flask-server
    ports:
      - "8000:8000"
    volumes:
      - ./flask-server:/usr/src/app
    environment:
      FLASK_ENV: development

  react-app:
    build: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/usr/src/app
      - /usr/src/app/node_modules
